FROM aspnet:3.1-vsdbg AS base
WORKDIR /src
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ./src .

RUN dotnet build './Pacco.APIGateway/Pacco.APIGateway.csproj' -c Debug -o /out
FROM build AS publish
RUN dotnet publish Pacco.APIGateway/Pacco.APIGateway.csproj -c Debug -o /out

# Building final image used in running container
FROM base AS final
WORKDIR /src
COPY --from=publish /out .

ENV ASPNETCORE_URLS http://*:80
ENV ASPNETCORE_ENVIRONMENT k8s
ENV NTRADA_CONFIG ntrada-async.k8s.yml
ENTRYPOINT ["dotnet", "Pacco.APIGateway.dll"]
